version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - proyecto-red

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    depends_on:
      - mariadb_auth
    restart: unless-stopped
    networks:
      - proyecto-red

  mariadb_auth:
    image: mariadb:10.5
    container_name: mariadb_auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mariadb_auth_data:/var/lib/mysql
    networks:
      - proyecto-red

  zabbix-mariadb:
    image: mariadb:10.5
    container_name: zabbix-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    volumes:
      - zabbix_db_data:/var/lib/mysql
    networks:
      - proyecto-red

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: zabbix-mariadb
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    depends_on:
      - zabbix-mariadb
    ports:
      - "10051:10051"
    networks:
      - proyecto-red

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-latest
    container_name: zabbix-web
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: zabbix-mariadb
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Madrid
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - proyecto-red

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-latest
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: agente-local
    networks:
      - proyecto-red

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    depends_on:
      - frontend
      - backend
    networks:
      - proyecto-red

volumes:
  mariadb_auth_data:
  zabbix_db_data:

networks:
  proyecto-red:
    driver: bridge










